
  name: webrtc-electron-kiosk
  version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
  summary: Single-line elevator pitch for your amazing snap # 79 char long summary
  description: |
    This is my-snap's description. You have a paragraph or two to tell the
    most important story about your snap. Keep it under 100 words though,
    we live in tweetspace and your description wants to look good in the snap
    store.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  apps:
    webrtc-electron-kiosk:
      command: desktop-launch "$SNAP/electron-helloworld/electron-snap-kiosk-starter"
      plugs:
      - browser-sandbox
      - network
      - network-bind
      - opengl
      - pulseaudio
      - wayland
      - x11
  plugs:
    browser-sandbox:
      interface: browser-support
      allow-sandbox: true

  parts:
    electron-helloworld:
      plugin: nodejs
      source: https://github.com/davidtoska/electron-snap-kiosk-starter.git
      after: [desktop-gtk2]
      override-build: |
        case $SNAPCRAFT_ARCH_TRIPLET in
          "i386-linux-gnu") ARCH="ia32";;
          "x86_64-linux-gnu") ARCH="x64";;
          "arm-linux-gnueabihf") ARCH="armv7l";;
          "aarch64-linux-gnu") ARCH="arm64";;
          *) echo "ERROR: electron does not support the '$SNAPCRAFT_ARCH_TRIPLET' architecture" && exit 1;;
        esac
        npm install electron-packager &&
        ./node_modules/.bin/electron-packager . --overwrite --platform=linux --arch=$ARCH --output=release-build --prune=true
        cp -v -R ./electron-snap-kiosk-starter-linux-$ARCH $SNAPCRAFT_PART_INSTALL/electron-helloworld
      stage-packages:
      - libasound2
      - libgconf-2-4
      - libnss3
      - libxss1
      - libxtst6

